services:
  amule:
    image: ngosang/amule
    restart: unless-stopped
    environment:
      - GUI_PWD=${EMULE_PASS}
      - WEBUI_PWD=${EMULE_PASS}
      - MOD_AUTO_RESTART_ENABLED=true
      - MOD_AUTO_RESTART_CRON= 0 6 * * *
      - MOD_AUTO_SHARE_ENABLED=false
      - MOD_AUTO_SHARE_DIRECTORIES=/incoming
      - MOD_FIX_KAD_GRAPH_ENABLED=true
      - MOD_FIX_KAD_BOOTSTRAP_ENABLED=true
    ports:
      - "4711:4711" # web ui
      - "4712:4712" # remote gui
      - "4662:4662" # ed2k tcp
      - "4665:4665/udp" # edk global search udp
      - "4672:4672/udp" # ed2k udp
    volumes:
      - amule:/home/amule/.aMule
      - /media/discos/incoming:/incoming
      - temp:/temp
volumes:
  amule:
  temp:
